// code/apps/astro01/src/lib/components/ng/todolist/addItem.component.ts
import { CommonModule } from '@angular/common'
import { ChangeDetectionStrategy, Component, ElementRef, viewChild } from '@angular/core'
import { takeUntilDestroyed, toObservable } from '@angular/core/rxjs-interop'
import { map, switchMap, tap } from 'rxjs'
import { getSubject } from '~/lib/common/util'
import { addTodo } from '~/lib/services/todolist.service'

@Component({
  selector: 'bb-add-item',
  imports: [CommonModule],
  template: `
    <header class="header">
      <h1>todos</h1>
      <form (submit)="submitBtn$.next(true); $event.preventDefault()">
        <input #inputRef class="new-todo" placeholder="What needs to be done?" />
      </form>
    </header>
  `,
  styles: ``,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AddItemComponent {
  inputRefS = viewChild.required<ElementRef<HTMLInputElement>>('inputRef')
  inputElem$ = toObservable(this.inputRefS).pipe(map((ref) => ref.nativeElement))

  submitBtn$ = getSubject<boolean>()

  submitSub = this.submitBtn$
    .pipe(
      switchMap(() => this.inputElem$),
      tap((inputElem) => {
        const v: string = inputElem.value
        if (v !== '') {
          addTodo(v ?? '')
          inputElem.value = ''
        }
      }),
      takeUntilDestroyed(),
    )
    .subscribe()

  focusSub = this.inputElem$
    .pipe(
      tap((elem) => elem.focus()),
      takeUntilDestroyed(),
    )
    .subscribe()
}

// code/apps/astro01/src/lib/components/svelte-todos/addItem.svelte
<script lang="ts">
  import { tap } from 'rxjs'
  import { onMount } from 'svelte'
  import { getSubject } from '~/lib/common/util'
  import { addTodo } from '~/lib/services/todolist.service'

  let inputRef: HTMLInputElement

  const submitBtn$ = getSubject<boolean>()

  const submitSub = submitBtn$
    .pipe(
      tap(() => {
        const v = inputRef?.value ?? ''
        if (v !== '') {
          addTodo(v ?? '')
          inputRef.value = ''
        }
      }),
    )
    .subscribe()

  onMount(() => {
    return () => {
      submitSub.unsubscribe()
    }
  })
</script>

<header class="header">
  <h1>todos</h1>
  <form on:submit|preventDefault={() => submitBtn$.next(true)}>
    <input
      class="new-todo"
      placeholder="What needs to be done?"
      bind:this={inputRef}
      autoFocus={true}
    />
  </form>
</header>
