// code/apps/astro01/src/lib/components/ng/todolist/footer.component.ts
import { CommonModule } from '@angular/common'
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { takeUntilDestroyed } from '@angular/core/rxjs-interop'
import { map, switchMap, tap } from 'rxjs'
import { getSubject } from '~/lib/common/util'
import {
  type todosFilterType,
  getTodos,
  getTodosFilter,
  removeAllTodosCompleted,
  setTodosFilter,
} from '~/lib/services/todolist.service'

@Component({
  selector: 'bb-footer',
  imports: [CommonModule],
  template: `
    <footer class="footer">
      <span class="todo-count">
        @if ((uncompletedCount$ | async) === 1) {
          1 uncompleted item left
        } @else {
          {{ uncompletedCount$ | async }} uncompleted items left
        }
      </span>
      <ul class="filters">
        <li>
          <a
            (click)="setTodosFilterBtn$.next('all'); $event.preventDefault()"
            href="#/"
            [ngClass]="{ selected: (todoFilter$ | async) === 'all' }"
          >
            All
          </a>
        </li>
        <li>
          <a
            (click)="setTodosFilterBtn$.next('active'); $event.preventDefault()"
            href="#/"
            [ngClass]="{ selected: (todoFilter$ | async) === 'active' }"
          >
            Active
          </a>
        </li>
        <li>
          <a
            (click)="setTodosFilterBtn$.next('completed'); $event.preventDefault()"
            href="#/"
            [ngClass]="{ selected: (todoFilter$ | async) === 'completed' }"
          >
            Completed
          </a>
        </li>
      </ul>
      <div>
        @if (isShowClearCompleted$ | async) {
          <button (click)="removeAllTodosBtn$.next(true)" class="clear-completed">
            Clear completed
          </button>
        }
      </div>
    </footer>
  `,
  styles: ``,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FooterComponent {
  removeAllTodosBtn$ = getSubject<boolean>()
  setTodosFilterBtn$ = getSubject<todosFilterType>()
  todos$ = getTodos()
  todoFilter$ = getTodosFilter()

  isShowClearCompleted$ = this.todos$.pipe(
    map((todos) => {
      const completedCount = todos.filter((a) => a.completed).length
      return completedCount !== 0
    }),
  )

  uncompletedCount$ = this.todos$.pipe(map((todos) => todos.filter((a) => !a.completed).length))

  setTodosFilterSub = this.setTodosFilterBtn$
    .pipe(
      tap((type) => setTodosFilter(type)),
      takeUntilDestroyed(),
    )
    .subscribe()

  removeAllTodosSub = this.removeAllTodosBtn$
    .pipe(
      switchMap(() => removeAllTodosCompleted()),
      takeUntilDestroyed(),
    )
    .subscribe()
}

// code/apps/astro01/src/lib/components/svelte-store-todolist/footer.svelte
<script lang="ts">
  import { take } from 'rxjs'
  import { onMount } from 'svelte'
  import { derived } from 'svelte/store'
  import { toStore, writeableFlexible } from '~/lib/common/rxjs-interop-svelte-store'
  import { getUUID } from '~/lib/common/util'
  import {
    getTodos,
    getTodosFilter,
    removeAllTodosCompleted,
    setTodosFilter,
    type todosFilterType,
  } from '~/lib/services/todolist.service'

  const removeAllTodosBtn$ = writeableFlexible<string>()
  const setTodosFilterBtn$ = writeableFlexible<todosFilterType>()

  const todos$ = toStore(getTodos())

  const isShowClearCompleted$ = derived(
    todos$,
    (todos, set, update) => {
      const completedCount = todos.filter((a) => a.completed).length
      set(completedCount !== 0)
    },
    false,
  )

  const uncompletedCount$ = derived(
    todos$,
    (todos, set, update) => {
      set(todos.filter((a) => !a.completed).length)
    },
    0,
  )

  const todoFilter$ = getTodosFilter()

  const setTodosFilterSub = setTodosFilterBtn$.subscribe((type) => {
    setTodosFilter(type)
  }, true)

  const removeAllTodosSub = removeAllTodosBtn$.subscribe(() => {
    removeAllTodosCompleted().pipe(take(1)).subscribe()
  }, true)

  onMount(() => {
    return () => {
      removeAllTodosSub()
      setTodosFilterSub()
    }
  })
</script>

<footer class="footer">
  <span class="todo-count">
    {$uncompletedCount$ === 1
      ? '1 uncompleted item left'
      : `${$uncompletedCount$} uncompleted items left`}
  </span>
  <ul class="filters">
    <li>
      <a
        on:click|preventDefault={() => setTodosFilterBtn$.set('all')}
        href="#/"
        class={$todoFilter$ === 'all' ? 'selected' : ''}>
        All
      </a>
    </li>
    <li>
      <a
        on:click|preventDefault={() => setTodosFilterBtn$.set('active')}
        href="#/"
        class={$todoFilter$ === 'active' ? 'selected' : ''}>
        Active
      </a>
    </li>
    <li>
      <a
        on:click|preventDefault={() => setTodosFilterBtn$.set('completed')}
        href="#/"
        class={$todoFilter$ === 'completed' ? 'selected' : ''}>
        Completed
      </a>
    </li>
  </ul>
  <div>
    {#if $isShowClearCompleted$}
      <button
        on:click|preventDefault={() => removeAllTodosBtn$.set(getUUID())}
        class="clear-completed">
        Clear completed
      </button>
    {/if}
  </div>
</footer>
