// code/apps/astro01/src/lib/components/react-todolist/app.tsx
import List from './list'
import './style.css'

export default function App() {
  return (
    <div className="min-w-xl">
      <List />
      <footer className="info">
        <p>
          Created by <a href="http://twitter.com/oscargodson">Bibby</a>
        </p>
        <p>
          Reference to <a href="http://todomvc.com">TodoMVC</a>
        </p>
      </footer>
    </div>
  )
}

// code/apps/astro01/src/lib/components/ng-todolist/app.component.ts
import { CommonModule } from '@angular/common'
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { ListComponent } from './list.component'

@Component({
  selector: 'bb-app',
  imports: [CommonModule, ListComponent],
  template: `
    <div class="app-ccc flex justify-center">
      <div class="max-w-xl min-w-2xl">
        <bb-list />
        <footer class="info">
          <p>Created by <a href="http://twitter.com/bibbynet">Bibby</a></p>
          <p>Reference to <a href="http://todomvc.com">TodoMVC</a></p>
        </footer>
      </div>
    </div>
  `,
  styles: `
    :host {
      display: contents;
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent {}
