// code/apps/astro01/src/lib/components/svelte-store-todolist/addItem.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { writeableFlexible } from '~/lib/common/rxjs-interop-svelte-store'
  import { getUUID } from '~/lib/common/util'
  import { addTodo } from '~/lib/services/todolist.service'

  let inputRef: HTMLInputElement

  const submitBtn$ = writeableFlexible<string>()

  const submitSub = submitBtn$.subscribe(() => {
    const v = inputRef?.value ?? ''
    if (v !== '') {
      addTodo(v ?? '')
      inputRef.value = ''
    }
  }, true)

  onMount(() => {
    return () => {
      submitSub()
    }
  })
</script>

<header class="header">
  <h1>todos</h1>
  <form on:submit|preventDefault={() => submitBtn$.set(getUUID())}>
    <input
      class="new-todo"
      placeholder="What needs to be done?"
      bind:this={inputRef}
      autoFocus={true}
    />
  </form>
</header>

// code/apps/astro01/src/lib/components/vue-todolist/addItem.vue
<template>
  <header class="header">
    <h1>todos</h1>
    <form @submit.prevent="submitBtn$.next(true)">
      <input
        class="new-todo"
        placeholder="What needs to be done?"
        ref="inputRef"
        :autoFocus="true"
      />
    </form>
  </header>
</template>

<script setup lang="ts">
import { tap } from 'rxjs'
import { onUnmounted, ref } from 'vue'
import { getSubject } from '~/lib/common/util'
import { addTodo } from '~/lib/services/todolist.service'

let inputRef = ref<HTMLInputElement>()

const submitBtn$ = getSubject<boolean>()

const submitSub = submitBtn$
  .pipe(
    tap(() => {
      const v = inputRef.value?.value ?? ''
      if (v !== '') {
        addTodo(v ?? '')
        inputRef.value!.value = ''
      }
    }),
  )
  .subscribe()

onUnmounted(() => {
  submitSub.unsubscribe()
})
</script>
