// code/apps/astro01/src/lib/components/menu.svelte
<script lang="ts">
  import { map } from 'rxjs'
  import { getWindow } from '~/lib/services/layout.service'
  const baseUrl = import.meta.env.BASE_URL

  export const menus = [
    {
      title: 'Home',
      path: baseUrl + '',
    },
  ]

  const location$ = getWindow().pipe(map((w) => w.location))
</script>

<ul class="flex">
  {#each menus as item}
    <li class="mr-2">
      <a
        class:text-red-5={($location$?.pathname ?? '') === item.path}
        class="text-blue-5 underline"
        href={item.path}
      >
        {item.title}
      </a>
    </li>
  {/each}
</ul>

// code/apps/astro01/src/lib/components/ng/menu.component.ts
import { CommonModule } from '@angular/common'
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { map } from 'rxjs'
import { getWindow } from '~/lib/services/layout.service'

@Component({
  selector: 'app-menu',
  imports: [CommonModule],
  template: `
    <ul class="flex">
      @for (item of menus; track item.path) {
        <li class="mr-2">
          <a
            [ngClass]="{ 'text-red-500': (localPathName$ | async) === item.path }"
            class="text-blue-500 underline"
            [href]="item.path"
          >
            {{ item.title }}
          </a>
        </li>
      }
    </ul>
  `,
  styles: ``,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MenuComponent {
  baseUrl = import.meta.env.BASE_URL

  menus = [
    {
      title: 'Home',
      path: this.baseUrl + '',
    }
  ]

  localPathName$ = getWindow().pipe(map((lo) => lo.location.pathname))
}
